# -*- coding: utf-8 -*-
"""Ejercicios_Pendientes_Simon.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zN8HmU69_jWz-Ek7Yvs4T4umQJ_gMf8c
"""

#Imprimir Hola Mundo
A = "Hola mundo"
print (A)

#Imprimir un numero entero ingresado por el usuario
n_entero = str = (input("Ingrese un numero entero" " "))
print ("El numero ingresado es", n_entero)

#Sumar dos numeros enteros
n1 = float(input("Intro número uno: "))
n2 = float(input("Intro numero dos: "))
suma = n1+n2
print("La suma es: ", suma)

#Multiplicacion 2 numeros reales ingresados por el usuario
n1 = float(input("Intro número uno: "))
n2 = float(input("Intro numero dos: "))
multiplicacion = n1*n2
print("La multiplicacion es: ", multiplicacion)

#Multiplicacion de 2 numeros reales
n1 = float (45)
n2 = float (3)
multiplicacion = n1*n2
print("La multiplicacion es: ", multiplicacion)

#Ejercicio 7 conceptos basicos POO
class Cuenta_bancaria:
    def __init__(self, numerodecuenta:int, propetario:str, balance:int):
        self.numerodecuenta = numerodecuenta
        self.propetario = propetario
        self.balance = balance