# -*- coding: utf-8 -*-
"""Sebastianruiz

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f5hOnXcqjUTyfxQ0idBfc4vJBN8g-3Ab
"""

fe = ["React", "JQuery", "Django"]
be = ["Python", "Java", "C++"]

print (fe)
print (be)

print (fe[1])
print (be[0])

print (fe[1:2])
print (be[1:2])

print (fe[0:2])
print (be[0:2])

fe[2] = "Laravel"
print (fe)

del be[1]
print (be)

be.append("Java")
print (be)

fe.reverse()
print (fe)

be.reverse()
print (be)

fe.sort()
print (fe)

be.sort()
print (be)

fe.clear()
print (fe)

fruta = ("manzana", "pera", "mandarina", "guayaba")
t1 = 4,2,3,5
t2 = ("Cabeza", [1,2,3], (4,5,6))
t3 = ("c","a","r","l","i")

print (fruta[3])
print (t1[0])
print (t2[1])
print (t3[4])

print (t2[1][1])

print (t2[2][0])

print (t3[-5])
print (t3[-1])

print (t3[0:5])
print (t3[:-4])
print (t3[4:])
print (t3[:])

t2[1][0] = "a"
print (t2)
t2[1][1] = "b"
print (t2)
t2[1][2] = "c"
print (t2)

t4 = t2 + fruta
print (t4)

del (t3)
print (t3)

fruta = fruta + ("Borojo", "Chontaduro")
print (fruta)

print (fruta.count("Borojo"))

print (fruta.index("Borojo"))

numeros = {1,2,3,4,5}

colores = {"Azul","Rojo", "Verde", "Amarillo","Negro"}
print (colores)

mezclado = {4,"Harry", True, 4.2, (6,7,8)}
print (mezclado)

num = {1,1,2,3,4,5}
print (num)

primos = set([2,3,5,7,11])
print (primos)

numeros = {(9,10), (11,12)}
print (numeros)

carros = {"Compañia": "Kia",
          "Country" : "Korea",
          "Rank" : 1}
print (carros)
print (carros["Compañia"])
print (carros["Country"])
carros["name"] = "Audi"
print (carros)

del carros["Rank"]
print (carros)

carros.pop("Country")
print(carros)

min = {'a':92, 'b': 48, 'c': 99}
may = {'A': 5, 'B':66, 'C': 67}
mezcla = min.copy()
mezcla.update(may)
print (mezcla)

numeros = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
pares = set()
for numero in numeros:
  if numero%2==0:
    pares.add (numero)
print (pares)