# -*- coding: utf-8 -*-
"""trabajo sololoy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ce0UKMDHqLkYVpSvnZIAZD2vbM4SICz3
"""

fe=["jquery","emberjs", "django"]
be=["c++", "java script", "C"]
print (fe)
print(be)

print (fe[1])
print (fe [0])

print (fe[1:2])
print (be[1:2])

del be [1]
print (be)

be.append ("C#")
print (be)

fe.sort()
print (fe)

be.sort ()
print (be)

fe.clear ()
print (fe)

fruta = ("Manzana", "Pera", "Mango", "Fresa")
t1= 1,7,8,9
t2 = ("Zapato", [1,2,3], (2,4,5,))
t3 = ("b", "e", "ll", "a", "q", "u", "e", "o")
print (fruta[3])
print (t1[0])
print(t2[1])
print (t3[4])

print (t2[1][1])

print (t2 [2][0])

print  (t3[-8])
print (t3[-1])

print (t3[0:8])
print (t3[:-7])
print (t3[7:])
print (t3[:])

t2  [1][0] = "a"
print (t2)
t2 [1][1] = "b"
print (t2)
t2[1][2]= "c"
print (t2)

t4 = t2 + fruta 
print (t4)

del (t3)

fruta = fruta + ("almirajó", "sapote")
print (fruta)

print (fruta.count("almirajó"))

print (fruta.index("almirajó"))

numeros = {1,2,3,4,5}

colores = {"dorado", "negro","rojo","azul"}
print (colores)

mezclado= {7, "sololoy larga", True, 5.3, (7,9,8)}
print (mezclado)

num= {1,1,2,3,4,5}
print (num)

numnerosprimos= set ([2,3,5,7,11])
print (numnerosprimos)

numeros={(9,10), (11,12)}
print (numeros)

carros ={"compañia":"kia", 
         "country": "korea",
         "rank": 1}
print (carros)
print (carros ["compañia"])
print (carros["country"])
carros ["name"]="audi"
print (carros)

del carros ["rank"]
print (carros )

carros.pop("country")
print (carros)

min={'a': 95,'b':98, 'c': 99 }
may= {'A': 65, 'B': 66, 'C': 67}
mezcla= min.copy()
mezcla.update (may)
print (mezcla)

numeros=[1,2,3,5,6]
pares= set ()
for numeros in numeros:
  if numeros%2==0:
    pares.add (numeros) 
  print (pares)